### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by crashd0wn** [codex-digital/cypher-stream#24]
Hello,
The username/password have to be passed in a single hash like { username: username, password: password }, not 2 separate arguments like it says in the documentation.

**Comment by brian-gates** [comment]
Indeed.  The documentation reflects 1.0.0-alpha, which is not what you get from `npm install cypher-stream`.  

I'll update the docs!

**Comment by brian-gates** [comment]
I've reverted to the old API for consistency's sake.
