### ISSUE TITLE
No operations allowed until you send an INIT message successfully

### ISSUE THREAD

**Issue by rvazarkar** [codex-digital/cypher-stream#25]
When running a basic test example, I get this error.

`{ [Error: No operations allowed until you send an INIT message successfully.]
  message: 'No operations allowed until you send an INIT message successfully.',
  code: 'Neo.ClientError.Request.Invalid' }`

```
var cypher = require('cypher-stream')('bolt://localhost','neo4j','neo4j')

cypher('MATCH (n:User) RETURN n LIMIT 1')
	.on('data', function(result){
		console.log(result)
	})
	.on('error', function(error){
		console.log(error)
	})
```

Installed using:
npm install cypher-stream@1.0.0-alpha

Am I missing something really obvious here? I don't see anything that requires anything else. I'm running neo4j 3.0.4 if that makes a difference as well

**Comment by brian-gates** [comment]
Seems like an issue with the underlying driver.

Looks like it'll be fixed with a newer version.  As soon as it's out I'll update cypher-stream.

https://github.com/neo4j/neo4j-javascript-driver/issues/119

https://github.com/neo4j/neo4j-javascript-driver/pull/125

**Comment by brian-gates** [comment]
See this comment:

> You see this error message because you have failed to log in to server with a correct authentication token. We've known the error is really bad as it hides the real error that it was and we have a bug fix card for this problem already.

https://github.com/neo4j/neo4j-javascript-driver/issues/119#issuecomment-239099794

**Comment by rvazarkar** [comment]
Seems to work fine if I change the following line in index.js:

`var driver  = neo4j.driver(url || 'bolt://localhost', auth(options.username, options.password));`

to

`var driver  = neo4j.driver(url || 'bolt://localhost', auth('neo4j','neo4j'));`

It looks like the options aren't being passed in properly?

**Comment by brian-gates** [comment]
Ah!  That very well may be the case.  We don't use the authentication internally so it's admittedly not well-tested.

If you want to submit a PR I'm happy to review it.  Otherwise I'll try to take a look a bit later today.

**Comment by brian-gates** [comment]
OH!  This is actually a documentation error.  This should work:

```
var cypher = require('cypher-stream')('bolt://localhost', { username: 'neo4j', password: 'neo4j' })
```

**Comment by rvazarkar** [comment]
Yep that did it. Thanks

**Comment by brian-gates** [comment]
FWIW, I'm not 100% sold on this API yet.

Feedback welcome.

**Comment by rvazarkar** [comment]
It does look like passwords that aren't neo4j don't seem to work, but that looks like an issue in the driver, not on your end.

The API shows a lot of promise performance wise, but it needs to work first =)

**Comment by rvazarkar** [comment]
I'll let you know how it stacks up performance wise after I do some testing. It shows promise on that end, but need to get it working first!

**Comment by brian-gates** [comment]
Really?  Authentication isn't working?  Seems like it _should_... Any more information you can provide would be appreciated.
