### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by gunjan008** [codex-digital/cypher-stream#34]
Hi,
Can you tell me, how can I pass authentication details using cypher-stream?
For example, if I have to use neo4j driver I could do something like
neo4j.driver("bolt://localhost", neo4j.auth.basic("neo4j", "neo4j"));

Thanks,

**Comment by gigonaut** [comment]
you _should_ be able to simply do:
```
var cypher = require('cypher-stream')("bolt://localhost", "neo4j", "neo4j");
```
